CREATE TABLE IF NOT EXISTS memo (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT(1),
title VARCHAR(80) NOT NULL,
content VARCHAR(200),
create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);